# Generated by Django 4.1 on 2024-08-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("phoenix", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="projectimage",
            name="project",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ProjectImage",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
